"use strict";
(() => {
 const dialog=document.querySelector('#demo-dialog'),content=document.querySelector('#demo-content');let opener;
 document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>opener?.focus());
 const demos={flashcard:['Kartu Pintar',flashcard],palindrome:['Cermin Kata',palindrome],picker:['Pilih Dulu',picker]};
 document.querySelectorAll('[data-demo]').forEach(button=>{button.hidden=false;button.addEventListener('click',()=>{opener=button;const demo=demos[button.dataset.demo];document.querySelector('#demo-title').textContent=demo[0];content.replaceChildren();demo[1]();dialog.showModal();});});
 function flashcard(){
  const cards=[['HTML','Bahasa markup untuk menyusun struktur dan isi halaman web.'],['CSS','Bahasa stylesheet untuk mengatur tampilan: warna, ukuran, jarak, dan layout.'],['JavaScript','Bahasa pemrograman untuk menambahkan logika dan interaksi pada halaman web.'],['Variabel','Tempat menyimpan nilai yang dapat digunakan oleh program.'],['Perulangan','Cara menjalankan serangkaian instruksi berulang kali sesuai kondisi.']];
  content.innerHTML='<p>Ketuk kartu untuk membuka penjelasan, lalu lanjutkan ke istilah berikutnya.</p><p id="card-position" class="card-position"></p><button id="study-card" type="button" class="flashcard" aria-pressed="false"><strong id="card-term"></strong><span id="card-explanation" hidden></span><small id="card-hint">Ketuk untuk melihat arti</small></button><div class="demo-actions"><button class="button secondary" type="button" id="card-prev">← Sebelumnya</button><button class="button" type="button" id="card-next">Berikutnya →</button></div>';
  let index=0,flipped=false;const card=document.querySelector('#study-card'),explanation=document.querySelector('#card-explanation'),prev=document.querySelector('#card-prev'),next=document.querySelector('#card-next');
  function render(){document.querySelector('#card-position').textContent='Kartu '+(index+1)+' dari '+cards.length;document.querySelector('#card-term').textContent=cards[index][0];explanation.textContent=cards[index][1];explanation.hidden=!flipped;card.setAttribute('aria-pressed',String(flipped));document.querySelector('#card-hint').textContent=flipped?'Ketuk untuk menyembunyikan arti':'Ketuk untuk melihat arti';prev.disabled=index===0;next.disabled=index===cards.length-1;}
  card.addEventListener('click',()=>{flipped=!flipped;render();});prev.addEventListener('click',()=>{if(index>0){index--;flipped=false;render();card.focus();}});next.addEventListener('click',()=>{if(index<cards.length-1){index++;flipped=false;render();card.focus();}});render();
 }
 function palindrome(){
  content.innerHTML='<p>Palindrom dibaca sama dari depan dan belakang, misalnya “katak”. Huruf besar, spasi, dan tanda baca diabaikan.</p><form id="mirror-form"><label for="mirror-input">Kata atau kalimat</label><input id="mirror-input" maxlength="200" placeholder="Contoh: Kasur rusak" required><div class="demo-actions"><button class="button" type="submit">Cek palindrom</button><button class="button secondary" type="reset">Bersihkan</button></div></form><output class="result" id="mirror-result" aria-live="polite">Hasil pemeriksaan muncul di sini.</output>';
  const form=document.querySelector('#mirror-form'),result=document.querySelector('#mirror-result');form.addEventListener('submit',event=>{event.preventDefault();const normalized=document.querySelector('#mirror-input').value.normalize('NFC').toLocaleLowerCase('id-ID').replace(/[^\p{L}\p{N}]/gu,'');if(!normalized){result.textContent='Masukkan setidaknya satu huruf atau angka.';return;}const reversed=Array.from(normalized).reverse().join('');result.textContent=normalized===reversed?'Ya, ini palindrom! Bentuk yang diperiksa: '+normalized+'.':'Bukan palindrom. Bentuk terbaliknya: '+reversed+'.';});form.addEventListener('reset',()=>{result.textContent='Hasil pemeriksaan muncul di sini.';});
 }
 function picker(){
  content.innerHTML='<p>Bingung memilih kegiatan? Tulis satu pilihan per baris, lalu ambil satu secara acak.</p><form id="picker-form"><label for="picker-input">Daftar pilihan</label><textarea id="picker-input" maxlength="2000" required aria-describedby="picker-help" placeholder="Membaca buku\nBelajar HTML\nMenggambar"></textarea><p id="picker-help" class="field-note">Masukkan 2–20 pilihan berbeda. Baris kosong diabaikan.</p><div class="demo-actions"><button class="button" type="submit">Pilih untukku ✧</button><button class="button secondary" type="reset">Mulai ulang</button></div></form><output class="result" id="picker-result" aria-live="polite">Pilihanmu akan muncul di sini.</output>';
  const form=document.querySelector('#picker-form'),result=document.querySelector('#picker-result');form.addEventListener('submit',event=>{event.preventDefault();const options=[],seen=new Set();for(const line of document.querySelector('#picker-input').value.split(/\r?\n/)){const choice=line.trim(),key=choice.toLocaleLowerCase('id-ID');if(choice&&!seen.has(key)){seen.add(key);options.push(choice);}}if(options.length<2||options.length>20){result.textContent='Isi 2 sampai 20 pilihan berbeda terlebih dahulu.';return;}const choice=options[Math.floor(Math.random()*options.length)];result.textContent='Pilihan kali ini: '+choice;});form.addEventListener('reset',()=>{result.textContent='Pilihanmu akan muncul di sini.';});
 }
})();
